/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PERIPHERALS_H_
#define _PERIPHERALS_H_

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "fsl_common.h"
#include "fsl_i2c.h"
#include "fsl_gpio.h"
#include "fsl_port.h"
#include "fsl_clock.h"
#include "fsl_ftm.h"

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus*/

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/
/* Definitions for BOARD_InitPeripherals functional group */
/* BOARD_InitPeripherals defines for I2C0 */
/* Definition of peripheral ID */
#define I2C_PERIPHERAL I2C0
/* Definition of the clock source */
#define I2C_CLKSRC I2C0_CLK_SRC
/* Alias for GPIOC peripheral */
#define BUS_C_GPIO GPIOC
/* Alias for GPIOD peripheral */
#define BUS_D_GPIO GPIOD
/* Alias for GPIOB peripheral */
#define OUTPUTS_GPIO GPIOB
/* Alias for GPIOA peripheral */
#define INPUTS_GPIO GPIOA
/* Definition of peripheral ID */
#define SYSCLK_PERIPHERAL FTM1
/* Definition of the clock source frequency */
#define SYSCLK_CLOCK_SOURCE CLOCK_GetFreq(kCLOCK_BusClk)
/* SYSCLK interrupt vector ID (number). */
#define SYSCLK_IRQN FTM1_IRQn
/* SYSCLK interrupt handler identifier. */
#define SYSCLK_IRQHANDLER FTM1_IRQHandler

/***********************************************************************************************************************
 * Global variables
 **********************************************************************************************************************/
extern const i2c_master_config_t I2C_config;
extern gpio_pin_config_t BUS_C_config[12];
extern gpio_pin_config_t BUS_D_config[12];
extern gpio_pin_config_t OUTPUTS_config[5];
extern gpio_pin_config_t INPUTS_config[6];
extern const ftm_config_t SYSCLK_config;

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/
void BOARD_InitPeripherals(void);

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void);

#if defined(__cplusplus)
}
#endif

#endif /* _PERIPHERALS_H_ */
