/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PERIPHERALS_H_
#define _PERIPHERALS_H_

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "fsl_common.h"
#include "fsl_clock.h"
#include "fsl_ftm.h"
#include "fsl_i2c.h"
#include "fsl_gpio.h"
#include "fsl_port.h"

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus*/

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/
/* Definitions for BOARD_InitPeripherals functional group */
/* Definition of peripheral ID */
#define FTM_SYSCLK_PERIPHERAL FTM1
/* Definition of the clock source frequency */
#define FTM_SYSCLK_CLOCK_SOURCE CLOCK_GetFreq(kCLOCK_BusClk)
/* FTM_SYSCLK interrupt vector ID (number). */
#define FTM_SYSCLK_IRQN FTM1_IRQn
/* FTM_SYSCLK interrupt handler identifier. */
#define FTM_SYSCLK_IRQHANDLER FTM1_IRQHandler
/* BOARD_InitPeripherals defines for I2C0 */
/* Definition of peripheral ID */
#define I2C_PERIPHERAL I2C0
/* Definition of the clock source */
#define I2C_CLKSRC I2C0_CLK_SRC
/* Alias for GPIOB peripheral */
#define GPIO_STDBY_GPIO GPIOB

/***********************************************************************************************************************
 * Global variables
 **********************************************************************************************************************/
extern const ftm_config_t FTM_SYSCLK_config;
extern const i2c_master_config_t I2C_config;
extern gpio_pin_config_t GPIO_STDBY_config[1];

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/
void BOARD_InitPeripherals(void);

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void);

#if defined(__cplusplus)
}
#endif

#endif /* _PERIPHERALS_H_ */
